#pragma once

#include <cstdint>

namespace pvz {
    enum class AdviceType : int32_t {
        kClickOnSun                = 0,
        kClickedOnSun              = 1,
        kClickedOnCoin             = 2,
        kSeedRefresh               = 3,
        kCantAffordPlant           = 4,
        kPlantGravebustersOnGraves = 5,
        kPlantLilypadOnWater       = 6,
        kPlantTanglekelpOnWater    = 7,
        kPlantSeashroomOnWater     = 8,
        kPlantPotatoeMineOnLily    = 9,
        kPlantWrongArtType         = 10,
        kPlantNeedPot              = 11,
        kPlantNotOnGrave           = 12,
        kPlantNotOnCrater          = 13,
        kCantPlantThere            = 14,
        kPlantNotOnWater           = 15,
        kPlantingNeedsGround       = 16,
        kBeghouledDragToMatch3     = 17,
        kBeghouledMatch3           = 18,
        kBeghouledMatch4           = 19,
        kBeghouledSaveSun          = 20,
        kBeghouledUseCrater1       = 21,
        kBeghouledUseCrater2       = 22,
        kPlantNotPassedLine        = 23,
        kPlantOnlyOnRepeaters      = 24,
        kPlantOnlyOnMelonpult      = 25,
        kPlantOnlyOnSunflower      = 26,
        kPlantOnlyOnSpikeweed      = 27,
        kPlantOnlyOnKernelpult     = 28,
        kPlantOnlyOnMagnetshroom   = 29,
        kPlantOnlyOnFumeshroom     = 30,
        kPlantOnlyOnLilypad        = 31,
        kPlantNeedsRepeater        = 32,
        kPlantNeedsMelonpult       = 33,
        kPlantNeedsSunflower       = 34,
        kPlantNeedsSpikeweed       = 35,
        kPlantNeedsKernelpult      = 36,
        kPlantNeedsMagnetshroom    = 37,
        kPlantNeedsFumeshroom      = 38,
        kPlantNeedsLilypad         = 39,
        kSlotMachinePull           = 40,
        kHugeWave                  = 41,
        kShovelRefresh             = 42,
        kPortalRelocating          = 43,
        kSlotMachineCollectSun     = 44,
        kDestoryPotsToFinisihLevel = 45,
        kUseShovelOnPots           = 46,
        kAlmostThere               = 47,
        kZombiquariumClickTrophy   = 48,
        kZombiquariumCollectSun    = 49,
        kZombiquariumClickToFeed   = 50,
        kZombiquariumBuySnorkel    = 51,
        kIZombiePlantsNotReal      = 52,
        kIZombieNotPassedLine      = 53,
        kIZombieLeftOfLine         = 54,
        kSlotMachineSpinAgain      = 55,
        kIZombieEatAllBrains       = 56,
        kPeashooterDied            = 57,
        kStinkySleeping            = 58,
        kBeghouledNoMoves          = 59,
        kPlantSunflower5           = 60,
        kPlantingNeedSleeping      = 61,
        kClickToContinue           = 62,
        kSurviveFlags              = 63,
        kUnlockedMode              = 64,
        NumAdviceTypes             = 65,
        kNone                      = -1,
    };

    enum class AnimType : int32_t {
        kNone     = 0,
        kOnce     = 1,
        kPingpong = 2,
        kLoop     = 3,
    };

    enum class AwardType : int32_t {
        kForLevel          = 0,
        kCreditsZombieNote = 1,
    };

    enum class BackgroundType : int32_t {
        k1Day           = 0,
        k2Night         = 1,
        k3Pool          = 2,
        k4Fog           = 3,
        k5Roof          = 4,
        k6Boss          = 5,
        kMushroomGarden = 6,
        kGreenHouse     = 7,
        kZombiquarium   = 8,
        kTreeOfWisdom   = 9,
    };

    enum class BoardResult : int32_t {
        kNone    = 0,
        kWon     = 1,
        kLost    = 2,
        kRestart = 3,
        kQuit    = 4,
        kQuitApp = 5,
        kCheat   = 6,
    };

    enum class ChallengePage : int32_t {
        kSurvival         = 0,
        kChallenge        = 1,
        kLimbo            = 2,
        kPuzzle           = 3,
        MaxChallangePages = 4,
    };

    enum class ChallengeState : int32_t {
        kNormal               = 0,
        kBeghouledMoving      = 1,
        kBeghouledFalling     = 2,
        kBeghouledNoMatches   = 3,
        kSlotMachineRolling   = 4,
        kStormFlash1          = 5,
        kStormFlash2          = 6,
        kStormFlash3          = 7,
        kZenFading            = 8,
        kScaryPotterMalleting = 9,
        kLastStandOnslaught   = 10,
        kTreeJustGrew         = 11,
        kTreeGiveWisdom       = 12,
        kTreeWaitingToBabble  = 13,
        kTreeBabbling         = 14,
    };

    enum class ChosenSeedState : int32_t {
        kFlyingToBank    = 0,
        kInBank          = 1,
        kFlyingToChooser = 2,
        kInChooser       = 3,
        kPacketHidden    = 4,
    };

    enum class CoinMotion : int32_t {
        kFromSky       = 0,
        kFromSkySlow   = 1,
        kFromPlant     = 2,
        kCoin          = 3,
        kLawnmowerCoin = 4,
        kFromPresent   = 5,
        kFromBoss      = 6,
    };

    enum class CoinType : int32_t {
        kNone                 = 0,
        kSilver               = 1,
        kGold                 = 2,
        kDiamond              = 3,
        kSun                  = 4,
        kSmallsun             = 5,
        kBigsun               = 6,
        kFinalSeedPacket      = 7,
        kTrophy               = 8,
        kShovel               = 9,
        kAlmanac              = 10,
        kCarkeys              = 11,
        kVase                 = 12,
        kWateringCan          = 13,
        kTaco                 = 14,
        kNote                 = 15,
        kUsableSeedPacket     = 16,
        kPresentPlant         = 17,
        kAwardMoneyBag        = 18,
        kAwardPresent         = 19,
        kAwardBagDiamond      = 20,
        kAwardSilverSunflower = 21,
        kAwardGoldSunflower   = 22,
        kChocolate            = 23,
        kAwardChocolate       = 24,
        kPresentMinigames     = 25,
        kPresentPuzzleMode    = 26,
    };

    enum class CrazyDaveState : int32_t {
        kOff            = 0,
        kEntering       = 1,
        kLeaving        = 2,
        kIdling         = 3,
        kTalking        = 4,
        kHandingTalking = 5,
        kHandingIdling  = 6,
    };

    enum class CreditsPhase : int32_t {
        kMain1 = 0,
        kMain2 = 1,
        kMain3 = 2,
        kEnd   = 3,
    };

    enum class CursorType : int32_t {
        kNormal               = 0,
        kPlantFromBank        = 1,
        kPlantFromUsableCoin  = 2,
        kPlantFromGlove       = 3,
        kPlantFromDuplicator  = 4,
        kPlantFromWheelBarrow = 5,
        kShovel               = 6,
        kHammer               = 7,
        kCobcannonTarget      = 8,
        kWateringCan          = 9,
        kFertilizer           = 10,
        kBugSpray             = 11,
        kPhonograph           = 12,
        kChocolate            = 13,
        kGlove                = 14,
        kMoneySign            = 15,
        kWheelbarrow          = 16,
        kTreeFood             = 17,
    };

    enum class DebugTextMode : int32_t {
        kNone        = 0,
        kZombieSpawn = 1,
        kMusic       = 2,
        kMemory      = 3,
        kCollision   = 4,
    };

    enum class DrawVariation : int32_t {
        kNormal             = 0,
        kImitater           = 1,
        kMarigoldWhite      = 2,
        kMarigoldMagenta    = 3,
        kMarigoldOrange     = 4,
        kMarigoldPink       = 5,
        kMarigoldLightBlue  = 6,
        kMarigoldRed        = 7,
        kMarigoldViolet     = 9,
        kMarigoldLavender   = 10,
        kMarigoldYellow     = 11,
        kMarigoldLightGreen = 12,
        kZenGarden          = 13,
        kZenGardenWater     = 14,
        kSproutNoFlowre     = 15,
        kImitaterLess       = 16,
        kAquarium           = 17,
    };

    enum class EffectType : int32_t {
        kParticle   = 0,
        kTrail      = 1,
        kReanim     = 2,
        kAttachment = 3,
        kOther      = 4,
    };

    enum class EmitterType : int32_t {
        kCircle            = 0,
        kBox               = 1,
        kBoxPath           = 2,
        kCirclePath        = 3,
        kCircleEvenSpacing = 4,
    };

    enum class EResult : int32_t {
        kDone          = 0,
        kNotStarted    = 1,
        kNotCompleted  = 2,
        kNotFound      = 3,
        kHttpError     = 4,
        kHttpRedirect  = 5,
        kAborted       = 6,
        kSocketError   = 7,
        kInvalidAddr   = 8,
        kConnectFail   = 9,
        kDisconnected  = 10,
        kInternalError = 11,
    };

    enum class FilterEffect : int32_t {
        kWashedOut       = 0,
        kLessWashedOut   = 1,
        kWhite           = 2,
        NumFilterEffects = 3,
        kNone            = -1,
    };

    enum class GameMode : int32_t {
        kAdventure                = 0,
        kSurvivalNormalStage1     = 1,
        kSurvivalNormalStage2     = 2,
        kSurvivalNormalStage3     = 3,
        kSurvivalNormalStage4     = 4,
        kSurvivalNormalStage5     = 5,
        kSurvivalHardStage1       = 6,
        kSurvivalHardStage2       = 7,
        kSurvivalHardStage3       = 8,
        kSurvivalHardStage4       = 9,
        kSurvivalHardStage5       = 10,
        kSurvivalEndlessStage1    = 11,
        kSurvivalEndlessStage2    = 12,
        kSurvivalEndlessStage3    = 13,
        kSurvivalEndlessStage4    = 14,
        kSurvivalEndlessStage5    = 15,
        kChallengeWarAndPeas      = 16,
        kChallengeWallnutBowling  = 17,
        kChallengeSlotMachine     = 18,
        kChallengeRainingSeeds    = 19,
        kChallengeBeghouled       = 20,
        kChallengeInvisighoul     = 21,
        kChallengeSeeingStars     = 22,
        kChallengeZombiquarium    = 23,
        kChallengeBeghouledTwist  = 24,
        kChallengeLittleTrouble   = 25,
        kChallengePortalCombat    = 26,
        kChallengeColumn          = 27,
        kChallengeBobsledBonanza  = 28,
        kChallengeSpeed           = 29,
        kChallengeWhackAZombie    = 30,
        kChallengeLastStand       = 31,
        kChallengeWarAndPeas2     = 32,
        kChallengeWallnutBowling2 = 33,
        kChallengePogoParty       = 34,
        kChallengeFinalBoss       = 35,
        kChallengeArtChallenge1   = 36,
        kChallengeSunnyDay        = 37,
        kChallengeResodded        = 38,
        kChallengeBigTime         = 39,
        kChallengeArtChallenge2   = 40,
        kChallengeAirRaid         = 41,
        kChallengeIce             = 42,
        kChallengeZenGarden       = 43,
        kChallengeHighGravity     = 44,
        kChallengeGraveDanger     = 45,
        kChallengeShovel          = 46,
        kChallengeStormyNight     = 47,
        kChallengeBungeeBlitz     = 48,
        kChallengeSquirrel        = 49,
        kTreeOfWisdom             = 50,
        kScaryPotter1             = 51,
        kScaryPotter2             = 52,
        kScaryPotter3             = 53,
        kScaryPotter4             = 54,
        kScaryPotter5             = 55,
        kScaryPotter6             = 56,
        kScaryPotter7             = 57,
        kScaryPotter8             = 58,
        kScaryPotter9             = 59,
        kScaryPotterEndless       = 60,
        kPuzzleIZombie1           = 61,
        kPuzzleIZombie2           = 62,
        kPuzzleIZombie3           = 63,
        kPuzzleIZombie4           = 64,
        kPuzzleIZombie5           = 65,
        kPuzzleIZombie6           = 66,
        kPuzzleIZombie7           = 67,
        kPuzzleIZombie8           = 68,
        kPuzzleIZombie9           = 69,
        kPuzzleIZombieEndless     = 70,
        NumGameModes              = 71,
    };

    enum class GameScenes : int32_t {
        kLoading    = 0,
        kMenu       = 1,
        kLevelIntro = 2,
        kPlaying    = 3,
        kZombiesWon = 4,
        kAward      = 5,
        kCredit     = 6,
        kChallenge  = 7,
    };

    enum class GardenType : int32_t {
        kMain        = 0,
        kMushroom    = 1,
        kWheelbarrow = 2,
        kAquarium    = 3,
    };

    enum class GridItemType : int32_t {
        kNone         = 0,
        kGravestone   = 1,
        kCrater       = 2,
        kLadder       = 3,
        kPortalCircle = 4,
        kPortalSquare = 5,
        kBrain        = 6,
        kScaryPot     = 7,
        kSquirrel     = 8,
        kZenTool      = 9,
        kStinky       = 10,
        kRake         = 11,
        kIzombieBrain = 12,
    };

    enum class GridItemState : int32_t {
        kNormal                 = 0,
        kGravestoneSpecial      = 1,
        kPortalClosed           = 2,
        kScaryPotQuestion       = 3,
        kScaryPotLeaf           = 4,
        kScaryPotZombie         = 5,
        kSquirrelWaiting        = 6,
        kSquirrelPeeking        = 7,
        kSquirrelRunningUp      = 8,
        kSquirrelRunningDown    = 9,
        kSquirrelRunningLeft    = 10,
        kSquirrelRunningRight   = 11,
        kSquirrelCaught         = 12,
        kSquirrelZombie         = 13,
        kZenToolWateringCan     = 14,
        kZenToolFertilizer      = 15,
        kZenToolBugSpray        = 16,
        kZenToolPhonograph      = 17,
        kZenToolGoldWateringCan = 18,
        kStinkyWalkingLeft      = 19,
        kStinkyTurningLeft      = 20,
        kStinkyWalkingRight     = 21,
        kStinkyTurningRight     = 22,
        kStinkySleeping         = 23,
        kStinkyFallingAsleep    = 24,
        kStinkyWakingUp         = 25,
        kRakeAttracting         = 26,
        kRakeWaiting            = 27,
        kRakeTriggered          = 28,
        kBrainSquished          = 29,
    };

    enum class GridSquareType : int32_t {
        kNone       = 0,
        kGrass      = 1,
        kDirt       = 2,
        kPool       = 3,
        kHighGround = 4,
    };

    enum class HelmType : int32_t {
        kNone        = 0,
        kTrafficCone = 1,
        kPail        = 2,
        kFootball    = 3,
        kDigger      = 4,
        kRedeyes     = 5,
        kHeadband    = 6,
        kBobsled     = 7,
        kWallnut     = 8,
        kTallnut     = 9,
    };

    enum class KeyCode : int32_t {
        kUnknown     = 0,
        kLbutton     = 1,
        kRbutton     = 2,
        kCancel      = 3,
        kMbutton     = 4,
        kBack        = 8,
        kTab         = 9,
        kClear       = 12,
        kReturn      = 13,
        kShift       = 16,
        kControl     = 17,
        kMenu        = 18,
        kPause       = 19,
        kCapital     = 20,
        kHangul      = 21,
        kHangeul     = 21,
        kKana        = 21,
        kJunja       = 23,
        kFinal       = 24,
        kKanji       = 25,
        kHanja       = 25,
        kEscape      = 27,
        kConvert     = 28,
        kNonconvert  = 29,
        kAccept      = 30,
        kModechange  = 31,
        kSpace       = 32,
        kPrior       = 33,
        kNext        = 34,
        kEnd         = 35,
        kHome        = 36,
        kLeft        = 37,
        kUp          = 38,
        kRight       = 39,
        kDown        = 40,
        kSelect      = 41,
        kPrint       = 42,
        kExecute     = 43,
        kSnapshot    = 44,
        kInsert      = 45,
        kDelete      = 46,
        kHelp        = 47,
        kAsciibegin  = 48,
        kAsciiend    = 90,
        kLwin        = 91,
        kRwin        = 92,
        kApps        = 93,
        kNumpad0     = 96,
        kNumpad1     = 97,
        kNumpad2     = 98,
        kNumpad3     = 99,
        kNumpad4     = 100,
        kNumpad5     = 101,
        kNumpad6     = 102,
        kNumpad7     = 103,
        kNumpad8     = 104,
        kNumpad9     = 105,
        kMultiply    = 106,
        kAdd         = 107,
        kSeparator   = 108,
        kSubtract    = 109,
        kDecimal     = 110,
        kDivide      = 111,
        kF1          = 112,
        kF2          = 113,
        kF3          = 114,
        kF4          = 115,
        kF5          = 116,
        kF6          = 117,
        kF7          = 118,
        kF8          = 119,
        kF9          = 120,
        kF10         = 121,
        kF11         = 122,
        kF12         = 123,
        kF13         = 124,
        kF14         = 125,
        kF15         = 126,
        kF16         = 127,
        kF17         = 128,
        kF18         = 129,
        kF19         = 130,
        kF20         = 131,
        kF21         = 132,
        kF22         = 133,
        kF23         = 134,
        kF24         = 135,
        kNumlock     = 144,
        kScroll      = 145,
        kAsciibegin2 = 179,
        kAsciiend2   = 224,

    };

    enum class LawnMowerState : int32_t {
        kRollingIn = 0,
        kReady     = 1,
        kTriggered = 2,
        kSquished  = 3,
    };

    enum class LawnMowerType : int32_t {
        kLawn       = 0,
        kPool       = 1,
        kRoof       = 2,
        kSuperMower = 3,
    };

    enum class MagnetItemType : int32_t {
        kNone            = 0,
        kPail1           = 1,
        kPail2           = 2,
        kPail3           = 3,
        kFootballHelmet1 = 4,
        kFootballHelmet2 = 5,
        kFootballHelmet3 = 6,
        kDoor1           = 7,
        kDoor2           = 8,
        kDoor3           = 9,
        kPogo1           = 10,
        kPogo2           = 11,
        kPogo3           = 12,
        kJackInTheBox    = 13,
        kLadder1         = 14,
        kLadder2         = 15,
        kLadder3         = 16,
        kLadderPlaced    = 17,
        kSilverCoin      = 18,
        kGoldCoin        = 19,
        kDiamond         = 20,
        kPickAxe         = 21,
    };

    enum class MessageStyle : int32_t {
        kOff                = 0,
        kTutorialLevel1     = 1,
        kTutorialLevel1Stay = 2,
        kTutorialLevel2     = 3,
        kTutorialLater      = 4,
        kTutorialLaterStay  = 5,
        kHintLong           = 6,
        kHintFast           = 7,
        kHintStay           = 8,
        kHintTallFast       = 9,
        kHintTall10Seconds  = 10,
        kHintTall8Seconds   = 11,
        kHintTallLong       = 12,
        kBigMiddle          = 13,
        kBigMiddleFast      = 14,
        kHouseName          = 15,
        kHugeWave           = 16,
        kSlotMachine        = 17,
        kZenGardenLong      = 18,
    };

    enum class MowerHeight : int32_t {
        kLand       = 0,
        kDownToPool = 1,
        kInPool     = 2,
        kUpToLand   = 3,
    };

    enum class MusicBurstState : int32_t {
        kOff       = 0,
        kStarting  = 1,
        kOn        = 2,
        kFinishing = 3,
    };

    enum class MusicDrumsState : int32_t {
        kOff       = 0,
        kOnQueued  = 1,
        kOn        = 2,
        kOffQueued = 3,
        kFading    = 4,
    };

    enum class MusicFile : int32_t {
        kMainMusic                = 1,
        kDrums                    = 2,
        kHihats                   = 3,
        kCreditsZombiesOnYourLawn = 4,
        NumMusicFiles             = 5,
        kNone                     = -1,
    };

    enum class MusicTune : int32_t {
        kDayGrasswalk             = 1,
        kNightMoongrains          = 2,
        kPoolWaterygraves         = 3,
        kFogRigormormist          = 4,
        kRoofGrazetheroof         = 5,
        kChooseYourSeeds          = 6,
        kTitleCrazyDaveMainTheme  = 7,
        kZenGarden                = 8,
        kPuzzleCerebrawl          = 9,
        kMinigameLoonboon         = 10,
        kConveyer                 = 11,
        kFinalBossBrainiacManiac  = 12,
        kCreditsZombiesOnYourLawn = 13,
        NumMusicTunes             = 14,
        kNone                     = -1,
    };

    enum class ParticleEffect : int32_t {
        kMelonsplash           = 0,
        kWintermelon           = 1,
        kFumecloud             = 2,
        kPopcornsplash         = 3,
        kPowie                 = 4,
        kJackexplode           = 5,
        kZombieHead            = 6,
        kZombieArm             = 7,
        kZombieTrafficCone     = 8,
        kZombiePail            = 9,
        kZombieHelmet          = 10,
        kZombieFlag            = 11,
        kZombieDoor            = 12,
        kZombieNewspaper       = 13,
        kZombieHeadlight       = 14,
        kPow                   = 15,
        kZombiePogo            = 16,
        kZombieNewspaperHead   = 17,
        kZombieBalloonHead     = 18,
        kSodRoll               = 19,
        kGraveStoneRise        = 20,
        kPlanting              = 21,
        kPlantingPool          = 22,
        kZombieRise            = 23,
        kGraveBuster           = 24,
        kGraveBusterDie        = 25,
        kPoolSplash            = 26,
        kIceSparkle            = 27,
        kSeedPacket            = 28,
        kTallNutBlock          = 29,
        kDoom                  = 30,
        kDiggerRise            = 31,
        kDiggerTunnel          = 32,
        kDancerRise            = 33,
        kPoolSparkly           = 34,
        kWallnutEatSmall       = 35,
        kWallnutEatLarge       = 36,
        kPeaSplat              = 37,
        kSpikeSplat            = 38,
        kButterSplat           = 39,
        kCabbageSplat          = 40,
        kPuffSplat             = 41,
        kStarSplat             = 42,
        kIceTrap               = 43,
        kSnowpeaSplat          = 44,
        kSnowpeaPuff           = 45,
        kSnowpeaTrail          = 46,
        kLanternShine          = 47,
        kSeedPacketPickup      = 48,
        kPotatoMine            = 49,
        kPotatoMineRise        = 50,
        kPuffshroomTrail       = 51,
        kPuffshroomMuzzle      = 52,
        kSeedPacketFlash       = 53,
        kWhackAZombieRise      = 54,
        kZombieLadder          = 55,
        kUmbrellaReflect       = 56,
        kSeedPacketPick        = 57,
        kIceTrapZombie         = 58,
        kIceTrapRelease        = 59,
        kZamboniSmoke          = 60,
        kGloomcloud            = 61,
        kZombiePogoHead        = 62,
        kZamboniTire           = 63,
        kZamboniExplosion      = 64,
        kZamboniExplosion2     = 65,
        kCatapultExplosion     = 66,
        kMowerCloud            = 67,
        kBossIceBall           = 68,
        kBlastmark             = 69,
        kCoinPickupArrow       = 70,
        kPresentPickup         = 71,
        kImitaterMorph         = 72,
        kMoweredZombieHead     = 73,
        kMoweredZombieArm      = 74,
        kZombieHeadPool        = 75,
        kZombieBossFireball    = 76,
        kFireballDeath         = 77,
        kIceballDeath          = 78,
        kIceballTrail          = 79,
        kFireballTrail         = 80,
        kBossExplosion         = 81,
        kScreenFlash           = 82,
        kTrophySparkle         = 83,
        kPortalCircle          = 84,
        kPortalSquare          = 85,
        kPottedPlantGlow       = 86,
        kPottedWaterPlantGlow  = 87,
        kPottedZenGlow         = 88,
        kMindControl           = 89,
        kVaseShatter           = 90,
        kVaseShatterLeaf       = 91,
        kVaseShatterZombie     = 92,
        kAwardPickupArrow      = 93,
        kZombieSeaweed         = 94,
        kZombieMustache        = 95,
        kZombieFutureGlasses   = 96,
        kPinata                = 97,
        kDustSquash            = 98,
        kDustFoot              = 99,
        kDaisy                 = 100,
        kCreditStrobe          = 101,
        kCreditsRayswipe       = 102,
        kCreditsZombieheadwipe = 103,
        kStarburst             = 104,
        kCreditsFog            = 105,
        NumParticles           = 106,
        kNone                  = -1,

    };

    enum class ParticleFieldType : int32_t {
        kInvalid           = 0,
        kFriction          = 1,
        kAcceleration      = 2,
        kAttractor         = 3,
        kMaxVelocity       = 4,
        kVelocity          = 5,
        kPosition          = 6,
        kSystemPosition    = 7,
        kGroundConstraint  = 8,
        kShake             = 9,
        kCircle            = 10,
        kAway              = 11,
        ParticleFieldCount = 12,
    };

    enum class PlantRowType : int32_t {
        kDirt       = 0,
        kNormal     = 1,
        kPool       = 2,
        kHighGround = 3,
    };

    enum class PlantState : int32_t {
        kNotready              = 0,
        kReady                 = 1,
        kDoingspecial          = 2,
        kSquashLook            = 3,
        kSquashPreLaunch       = 4,
        kSquashRising          = 5,
        kSquashFalling         = 6,
        kSquashDoneFalling     = 7,
        kGravebusterLanding    = 8,
        kGravebusterEating     = 9,
        kChomperBiting         = 10,
        kChomberBitingGotOne   = 11,
        kChomperBitingMissed   = 12,
        kChomperDigesting      = 13,
        kChomperSwallowing     = 14,
        kPotatoRising          = 15,
        kPotatoArmed           = 16,
        kPotatoMashed          = 17,
        kSpikeweedAttacking    = 18,
        kSpikeweedAttacking2   = 19,
        kScaredyshroomLowering = 20,
        kScaredyshroomScared   = 21,
        kScaredyshroomRaising  = 22,
        kSunshroomSmall        = 23,
        kSunshroomGrowing      = 24,
        kSunshroomBig          = 25,
        kMagnetshroomSucking   = 26,
        kMagnetshroomCharging  = 27,
        kBowlingUp             = 28,
        kBowlingDown           = 29,
        kCactusLow             = 30,
        kCactusRising          = 31,
        kCactusHigh            = 32,
        kCactusLowering        = 33,
        kTanglekelpGrabbing    = 34,
        kCobcannonArming       = 35,
        kCobcannonLoading      = 36,
        kCobcannonReady        = 37,
        kCobcannonFiring       = 38,
        kKernelpultButter      = 39,
        kUmbrellaTriggered     = 40,
        kUmbrellaReflecting    = 41,
        kImitaterMorphing      = 42,
        kZenGardenWatered      = 43,
        kZenGardenNeedy        = 44,
        kZenGardenHappy        = 45,
        kMarigoldEnding        = 46,
        kFlowerpotInvulnerable = 47,
        kLilypadInvulnerable   = 48,
    };

    enum class PlantSubClass : int32_t {
        kNormal = 0,
        kShooter = 1,
    };

    enum class PlantWeapon : int32_t {
        kPrimary = 0,
        kSecondary = 1,
    };

    enum class PottedPlantAge : int32_t {
        kSprout = 0,
        kSmall  = 1,
        kMedium = 2,
        kFull   = 3,
    };

    enum class PottedPlantNeed : int32_t {
        kNone       = 0,
        kWater      = 1,
        kFertilizer = 2,
        kBugspray   = 3,
        kPhonograph = 4,
    };

    enum class ProjectileMotion : int32_t {
        kStraight     = 0,
        kLobbed       = 1,
        kThreepeater  = 2,
        kBee          = 3,
        kBeeBackwards = 4,
        kPuff         = 5,
        kBackwards    = 6,
        kStar         = 7,
        kFloatOver    = 8,
        kHoming       = 9,
    };

    enum class ProjectileType : int32_t {
        kPea         = 0,
        kSnowpea     = 1,
        kCabbage     = 2,
        kMelon       = 3,
        kPuff        = 4,
        kWintermelon = 5,
        kFireball    = 6,
        kStar        = 7,
        kSpike       = 8,
        kBasketball  = 9,
        kKernel      = 10,
        kCobbig      = 11,
        kButter      = 12,
        kZombiePea   = 13,
    };

    enum class ReanimationType : int32_t {
        kLoadbarSprout           = 0,
        kLoadbarZombiehead       = 1,
        kSodroll                 = 2,
        kFinalWave               = 3,
        kPeashooter              = 4,
        kWallnut                 = 5,
        kLilypad                 = 6,
        kSunflower               = 7,
        kLawnmower               = 8,
        kReadysetplant           = 9,
        kCherrybomb              = 10,
        kSquash                  = 11,
        kDoomshroom              = 12,
        kSnowpea                 = 13,
        kRepeater                = 14,
        kSunshroom               = 15,
        kTallnut                 = 16,
        kFumeshroom              = 17,
        kPuffshroom              = 18,
        kHypnoshroom             = 19,
        kChomper                 = 20,
        kZombie                  = 21,
        kSun                     = 22,
        kPotatomine              = 23,
        kSpikeweed               = 24,
        kSpikerock               = 25,
        kThreepeater             = 26,
        kMarigold                = 27,
        kIceshroom               = 28,
        kZombieFootball          = 29,
        kZombieNewspaper         = 30,
        kZombieZamboni           = 31,
        kSplash                  = 32,
        kJalapeno                = 33,
        kJalapenoFire            = 34,
        kCoinSilver              = 35,
        kZombieCharred           = 36,
        kZombieCharredImp        = 37,
        kZombieCharredDigger     = 38,
        kZombieCharredZamboni    = 39,
        kZombieCharredCatapult   = 40,
        kZombieCharredGargantuar = 41,
        kScrareyshroom           = 42,
        kPumpkin                 = 43,
        kPlantern                = 44,
        kTorchwood               = 45,
        kSplitpea                = 46,
        kSeashroom               = 47,
        kBlover                  = 48,
        kFlowerPot               = 49,
        kCactus                  = 50,
        kDancer                  = 51,
        kTanglekelp              = 52,
        kStarfruit               = 53,
        kPolevaulter             = 54,
        kBalloon                 = 55,
        kGargantuar              = 56,
        kImp                     = 57,
        kDigger                  = 58,
        kDiggerDirt              = 59,
        kZombieDolphinrider      = 60,
        kPogo                    = 61,
        kBackupDancer            = 62,
        kBobsled                 = 63,
        kJackinthebox            = 64,
        kSnorkel                 = 65,
        kBungee                  = 66,
        kCatapult                = 67,
        kLadder                  = 68,
        kPuff                    = 69,
        kSleeping                = 70,
        kGraveBuster             = 71,
        kZombiesWon              = 72,
        kMagnetshroom            = 73,
        kBoss                    = 74,
        kCabbagepult             = 75,
        kKernelpult              = 76,
        kMelonpult               = 77,
        kCoffeebean              = 78,
        kUmbrellaleaf            = 79,
        kGatlingpea              = 80,
        kCattail                 = 81,
        kGloomshroom             = 82,
        kBossIceball             = 83,
        kBossFireball            = 84,
        kCobcannon               = 85,
        kGarlic                  = 86,
        kGoldMagnet              = 87,
        kWinterMelon             = 88,
        kTwinSunflower           = 89,
        kPoolCleaner             = 90,
        kRoofCleaner             = 91,
        kFirePea                 = 92,
        kImitater                = 93,
        kYeti                    = 94,
        kBossDriver              = 95,
        kLawnMoweredZombie       = 96,
        kCrazyDave               = 97,
        kTextFadeOn              = 98,
        kHammer                  = 99,
        kSlotMachineHandle       = 100,
        kCreditsFootball         = 101,
        kCreditsJackbox          = 102,
        kSelectorScreen          = 103,
        kPortalCircle            = 104,
        kPortalSquare            = 105,
        kZengardenSprout         = 106,
        kZengardenWateringcan    = 107,
        kZengardenFertilizer     = 108,
        kZengardenBugspray       = 109,
        kZengardenPhonograph     = 110,
        kDiamond                 = 111,
        kZombieHand              = 112,
        kStinky                  = 113,
        kRake                    = 114,
        kRainCircle              = 115,
        kRainSplash              = 116,
        kZombieSurprise          = 117,
        kCoinGold                = 118,
        kTreeOfWisdom            = 119,
        kTreeOfWisdomClouds      = 120,
        kTreeFood                = 121,
        kCreditsMain             = 122,
        kCreditsMain2            = 123,
        kCreditsMain3            = 124,
        kZombieCreditsDance      = 125,
        kCreditsStage            = 126,
        kCreditsBigbrain         = 127,
        kCreditsFlowerPetals     = 128,
        kCreditsInfantry         = 129,
        kCreditsThroat           = 130,
        kCreditsCrazydave        = 131,
        kCreditsBossdance        = 132,
        kZombieCreditsScreenDoor = 133,
        kZombieCreditsConehead   = 134,
        kCreditsZombiearmy1      = 135,
        kCreditsZombiearmy2      = 136,
        kCreditsTombstones       = 137,
        kCreditsSolarpower       = 138,
        kCreditsAnyhour          = 139,
        kCreditsWearetheundead   = 140,
        kCreditsDiscolights      = 141,
        NumReanims               = 142,
        kNone                    = -1,
    };

    enum class ReanimLoopType : int32_t {
        kLoop                         = 0,
        kLoopFullLastFrame            = 1,
        kPlayOnce                     = 2,
        kPlayOnceAndHold              = 3,
        kPlayOnceFullLastFrame        = 4,
        kPlayOnceFullLastFrameAndHold = 5,
    };

    enum class ScaryPotType : int32_t {
        kNone   = 0,
        kSeed   = 1,
        kZombie = 2,
        kSun    = 3,
    };

    enum class SeedType : int32_t {
        kPeashooter             = 0,
        kSunflower              = 1,
        kCherrybomb             = 2,
        kWallnut                = 3,
        kPotatomine             = 4,
        kSnowpea                = 5,
        kChomper                = 6,
        kRepeater               = 7,
        kPuffshroom             = 8,
        kSunshroom              = 9,
        kFumeshroom             = 10,
        kGravebuster            = 11,
        kHypnoshroom            = 12,
        kScaredyshroom          = 13,
        kIceshroom              = 14,
        kDoomshroom             = 15,
        kLilypad                = 16,
        kSquash                 = 17,
        kThreepeater            = 18,
        kTanglekelp             = 19,
        kJalapeno               = 20,
        kSpikeweed              = 21,
        kTorchwood              = 22,
        kTallnut                = 23,
        kSeashroom              = 24,
        kPlantern               = 25,
        kCactus                 = 26,
        kBlover                 = 27,
        kSplitpea               = 28,
        kStarfruit              = 29,
        kPumpkinshell           = 30,
        kMagnetshroom           = 31,
        kCabbagepult            = 32,
        kFlowerpot              = 33,
        kKernelpult             = 34,
        kInstantCoffee          = 35,
        kGarlic                 = 36,
        kUmbrella               = 37,
        kMarigold               = 38,
        kMelonpult              = 39,
        kGatlingpea             = 40,
        kTwinsunflower          = 41,
        kGloomshroom            = 42,
        kCattail                = 43,
        kWintermelon            = 44,
        kGoldMagnet             = 45,
        kSpikerock              = 46,
        kCobcannon              = 47,
        kImitater               = 48,
        kExplodeONut            = 49,
        kGiantWallnut           = 50,
        kSprout                 = 51,
        kLeftpeater             = 52,
        numSeedTypes            = 53,
        kBeghouledButtonShuffle = 54,
        kBeghouledButtonCrater  = 55,
        kSlotMachineSun         = 56,
        kSlotMachineDiamond     = 57,
        kZombiquariumSnorkle    = 58,
        kZombiquariumTrophy     = 59,
        kZombieNormal           = 60,
        kZombieTrafficCone      = 61,
        kZombiePolevaulter      = 62,
        kZombiePail             = 63,
        kZombieLadder           = 64,
        kZombieDigger           = 65,
        kZombieBungee           = 66,
        kZombieFootball         = 67,
        kZombieBalloon          = 68,
        kZombieScreenDoor       = 69,
        kZomboni                = 70,
        kZombiePogo             = 71,
        kZombieDancer           = 72,
        kZombieGargantuar       = 73,
        kZombieImp              = 74,
        kNone                   = -1,
    };

    enum class SeedChooserState : int32_t {
        kNormal   = 0,
        kViewLawn = 1,
    };

    enum class SelectorAnimState : int32_t {
        kOpen     = 0,
        kNewUser  = 1,
        kShowSign = 2,
        kIdle     = 3,
    };

    enum class ShieldType : int32_t {
        kNone      = 0,
        kDoor      = 1,
        kNewspaper = 2,
        kLadder    = 3,
    };

    enum class TodCurves : int32_t {
        kConstant         = 0,
        kLinear           = 1,
        kEaseIn           = 2,
        kEaseOut          = 3,
        kEaseInOut        = 4,
        kEaseInOutWeak    = 5,
        kFastInOut        = 6,
        kFastInOutWeak    = 7,
        kWeakFastInOut    = 8,
        kBounce           = 9,
        kBounceFastMiddle = 10,
        kBounceSlowMiddle = 11,
        kSinWave          = 12,
        kEaseSinWave      = 13,
    };

    enum class TrailType : int32_t {
        kIce  = 0,
        kNone = -1,
    };

    enum class TutorialState : int32_t {
        kOff                        = 0,
        kLevel1PickUpPeashooter     = 1,
        kLevel1PlantPeashooter      = 2,
        kLevel1RefreshPeashooter    = 3,
        kLevel1Completed            = 4,
        kLevel2PickUpSunflower      = 5,
        kLevel2PlantSunflower       = 6,
        kLevel2RefreshSunflower     = 7,
        kLevel2Completed            = 8,
        kMoresunPickUpSunflower     = 9,
        kMoresunPlantSunflower      = 10,
        kMoresunRefreshSunflower    = 11,
        kMoresunCompleted           = 12,
        kSlotMachinePull            = 13,
        kSlotMachineCompleted       = 14,
        kShovelPickup               = 15,
        kShovelDig                  = 16,
        kShovelKeepDigging          = 17,
        kShovelCompleted            = 18,
        kZombiquariumBuySnorkel     = 19,
        kZombiquariumBoughtSnorkel  = 20,
        kZombiquariumClickTrophy    = 21,
        kZenGardenPickupWater       = 22,
        kZenGardenWaterPlant        = 23,
        kZenGardenKeepWatering      = 24,
        kZenGardenVisitStore        = 25,
        kZenGardenFertilizePlants   = 26,
        kZenGardenCompleted         = 27,
        kWhackAZombieBeforePickSeed = 28,
        kWhackAZombiePickSeed       = 29,
        kWhackAZombieCompleted      = 30,
    };

    enum class UnlockingState : int32_t {
        kOff     = 0,
        kShaking = 1,
        kFading  = 2,
    };

    enum class ZombieAttackType : int32_t {
        kChew      = 0,
        kDriveOver = 1,
        kVault     = 2,
        kLadder    = 3,
    };

    enum class ZombieHeight : int32_t {
        kZombieNormal         = 0,
        kInToPool             = 1,
        kOutOfPool            = 2,
        kDraggedUnder         = 3,
        kUpToHighGround       = 4,
        kDownOffHighGround    = 5,
        kUpLadder             = 6,
        kFalling              = 7,
        kInToChimney          = 8,
        kGettingBungeeDropped = 9,
        kZombiquarium         = 10,
    };

    enum class ZombiePhase : int32_t {
        kZombieNormal                   = 0,
        kZombieDying                    = 1,
        kZombieBurned                   = 2,
        kZombieMowered                  = 3,
        kBungeeDiving                   = 4,
        kBungeeDivingScreaming          = 5,
        kBungeeAtBottom                 = 6,
        kBungeeGrabbing                 = 7,
        kBungeeRising                   = 8,
        kBungeeHitOuchy                 = 9,
        kBungeeCutscene                 = 10,
        kPolevaulterPreVault            = 11,
        kPolevaulterInVault             = 12,
        kPolevaulterPostVault           = 13,
        kRisingFromGrave                = 14,
        kJackInTheBoxRunning            = 15,
        kJackInTheBoxPopping            = 16,
        kBobsledSliding                 = 17,
        kBobsledBoarding                = 18,
        kBobsledCrashing                = 19,
        kPogoBouncing                   = 20,
        kPogoHighBounce1                = 21,
        kPogoHighBounce2                = 22,
        kPogoHighBounce3                = 23,
        kPogoHighBounce4                = 24,
        kPogoHighBounce5                = 25,
        kPogoHighBounce6                = 26,
        kPogoForwardBounce2             = 27,
        kPogoForwardBounce7             = 28,
        kNewspaperReading               = 29,
        kNewspaperMaddening             = 30,
        kNewspaperMad                   = 31,
        kDiggerTunneling                = 32,
        kDiggerRising                   = 33,
        kDiggerTunnelingPauseWithoutAxe = 34,
        kDiggerRiseWithoutAxe           = 35,
        kDiggerStunned                  = 36,
        kDiggerWalking                  = 37,
        kDiggerWalkingWithoutAxe        = 38,
        kDiggerCutscene                 = 39,
        kDancerDancingIn                = 40,
        kDancerSnappingFingers          = 41,
        kDancerSnappingFingersWithLight = 42,
        kDancerSnappingFingersHold      = 43,
        kDancerDancingLeft              = 44,
        kDancerWalkToRaise              = 45,
        kDancerRaiseLeft1               = 46,
        kDancerRaiseRight1              = 47,
        kDancerRaiseLeft2               = 48,
        kDancerRaiseRight2              = 49,
        kDancerRising                   = 50,
        kDolphinWalking                 = 51,
        kDolphinIntoPool                = 52,
        kDolphinRiding                  = 53,
        kDolphinInJump                  = 54,
        kDolphinWalkingInPool           = 55,
        kDolphinWalkingWithoutDolphin   = 56,
        kSnorkelWalking                 = 57,
        kSnorkelIntoPool                = 58,
        kSnorkelWalkingInPool           = 59,
        kSnorkelUpToEat                 = 60,
        kSnorkelEatingInPool            = 61,
        kSnorkelDownFromEat             = 62,
        kZombiquariumAccel              = 63,
        kZombiquariumDrift              = 64,
        kZombiquariumBackAndForth       = 65,
        kZombiquariumBite               = 66,
        kCatapultLaunching              = 67,
        kCatapultReloading              = 68,
        kGargantuarThrowing             = 69,
        kGargantuarSmashing             = 70,
        kImpGettingThrown               = 71,
        kImpLanding                     = 72,
        kBalloonFlying                  = 73,
        kBalloonPopping                 = 74,
        kBalloonWalking                 = 75,
        kLadderCarrying                 = 76,
        kLadderPlacing                  = 77,
        kBossEnter                      = 78,
        kBossIdle                       = 79,
        kBossSpawning                   = 80,
        kBossStomping                   = 81,
        kBossBungeesEnter               = 82,
        kBossBungeesDrop                = 83,
        kBossBungeesLeave               = 84,
        kBossDropRv                     = 85,
        kBossHeadEnter                  = 86,
        kBossHeadIdleBeforeSpit         = 87,
        kBossHeadIdleAfterSpit          = 88,
        kBossHeadSpit                   = 89,
        kBossHeadLeave                  = 90,
        kYetiRunning                    = 91,
        kSquashPreLaunch                = 92,
        kSquashRising                   = 93,
        kSquashFalling                  = 94,
        kSquashDoneFalling              = 95,
    };

    enum class ZombieType : int32_t {
        kNormal           = 0,
        kFlag             = 1,
        kTrafficCone      = 2,
        kPolevaulter      = 3,
        kPail             = 4,
        kNewspaper        = 5,
        kDoor             = 6,
        kFootball         = 7,
        kDancer           = 8,
        kBackupDancer     = 9,
        kDuckyTube        = 10,
        kSnorkel          = 11,
        kZamboni          = 12,
        kBobsled          = 13,
        kDolphinRider     = 14,
        kJackInTheBox     = 15,
        kBalloon          = 16,
        kDigger           = 17,
        kPogo             = 18,
        kYeti             = 19,
        kBungee           = 20,
        kLadder           = 21,
        kCatapult         = 22,
        kGargantuar       = 23,
        kImp              = 24,
        kBoss             = 25,
        kPeaHead          = 26,
        kWallnutHead      = 27,
        kJalapenoHead     = 28,
        kGatlingHead      = 29,
        kSquashHead       = 30,
        kTallnutHead      = 31,
        kRedeyeGargantuar = 32,
        kZombatar         = 33,
        kInvalid          = -1,
    };
} // namespace pvz
